name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        java:
          - 21
        example:
          - weather
          - echo-kotlin

    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Verify examples
        working-directory: examples/${{ matrix.example }}
#        run: mvn verify --no-transfer-progress
        run: mvn verify --no-transfer-progress -Dtachyon-server.version=1.0.0-beta.3

      - name: Publish test results
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: 'examples/${{ matrix.example }}/target/*-reports/TEST-*.xml'
          check_name: 'Test Report: ${{ matrix.example }} (JDK ${{ matrix.java }})'
          detailed_summary: true
          flaky_summary: true
          include_passed: false
          fail_on_failure: true
          require_tests: true
          comment: true
          job_summary: true
